arch:
  - arm64
language: node_js
node_js:
  - 14.17.3
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - sleep 3
  - npm test
deploy:
  provider: heroku
  api_key: $api_key
  app: $app
